// This file was auto-generated by ML.NET Model Builder. 

using System;
using MachineLearningTestML.Model;

namespace MachineLearningTestML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            begin:
            Console.WriteLine("Enter text to predict: ");
            string aux = Console.ReadLine();

            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col1 = aux,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");
            Console.WriteLine($"Col1: {sampleData.Col1}");
            Console.WriteLine($"\n\nPredicted Col0 value {predictionResult.Prediction} \nPredicted Col0 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();

            while (aux != "stop")
            {
                Console.Clear();
                goto begin;
            }
        }
    }
}
